services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_iot
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD:-admin123}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana_iot
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
      
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_iot
    ports:
      - "5678:5678"
    environment:
      - N8N_GENERIC_TIMEZONE=Europe/Madrid
      - WEATHER_API=${WEATHER_API}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - influxdb